"""
ml_preprocessing_pipeline_v4.py

Preprocessing pipeline for the thesis ML training scripts (v4).

Changes vs v3:
    1. DATASET_PATHS now point to the v3 ML-ready CSVs (output of
       long_horizon_and_feature_engineering.py).
    2. New: per-ticker minimum history filter (default 500 rows).
       Tickers with fewer rows are dropped before any split.
    3. New: train-only winsorization at 1% / 99% percentiles.
       Bounds saved in metadata['winsor_bounds'] so the same clip
       can be applied at live inference time. Bounded features
       (cyclic encodings, percentile ranks, drawdown) are skipped
       automatically.
    4. New: 4-way chronological split with purge gaps:
            train -> val_select -> val_calib -> test
       val_select is used for model selection and threshold reporting,
       val_calib is held out and used only for isotonic calibration.
       This breaks the optimism bias of using a single val fold for
       both selection and calibration that we observed in v3.
    5. prepare_tabular_data now returns 9 objects:
            X_train, y_train,
            X_val_select, y_val_select,
            X_val_calib, y_val_calib,
            X_test, y_test,
            metadata
    6. New: optional dump of split CSVs to a configurable folder
       (DEFAULT_OUTPUT_DIR) for offline inspection.
    7. get_horizon_feature_list updated for the new feature set.
       Cyclic calendar features and regime-aware features are kept
       across all horizons.

Environment: thesis_env (Anaconda), Python 3.x
"""

# Importing the libraries
import os
import sys
import warnings
from datetime import datetime

import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler

warnings.filterwarnings("ignore")


# ============================================================
# TERMINAL OUTPUT CAPTURE
# ============================================================

class TeeLogger:
    """
    Writes every print output both to the terminal and to a text file.
    This keeps the VS Code terminal output visible while also preserving
    a reproducible execution log for the thesis documentation.
    """

    def __init__(self, *streams):
        self.streams = streams

    def write(self, message):
        for stream in self.streams:
            stream.write(message)
            stream.flush()

    def flush(self):
        for stream in self.streams:
            stream.flush()


def create_terminal_output_log_file(output_dir=None):
    """Creates the output folder and returns a timestamped terminal log path."""
    if output_dir is None:
        output_dir = TERMINAL_OUTPUT_DIR
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return os.path.join(output_dir, f"ml_preprocessing_pipeline_v4_terminal_output_{timestamp}.txt")



# ============================================================
# CENTRAL DATASET PATH CONFIGURATION (v3 CSVs)
# ============================================================

DATASET_PATHS = {
    "CRYPTO": (
        r"C:\Users\grego\OneDrive\Υπολογιστής\Π.Μ.Σ. ΣΤΗΝ ΑΝΑΛΥΤΙΚΗ ΤΩΝ ΕΠΙΧΕΙΡΗΣΕΩΝ & "
        r"ΣΤΗΝ ΕΠΙΣΤΗΜΗ ΤΩΝ ΔΕΔΟΜΕΝΩΝ\ΔΙΠΛΩΜΑΤΙΚΗ\CSV Files"
        r"\5. Long Horizon And Features Addition\DATASET_CRYPTO_ML_READY_v3.csv"
    ),
    "FOREX": (
        r"C:\Users\grego\OneDrive\Υπολογιστής\Π.Μ.Σ. ΣΤΗΝ ΑΝΑΛΥΤΙΚΗ ΤΩΝ ΕΠΙΧΕΙΡΗΣΕΩΝ & "
        r"ΣΤΗΝ ΕΠΙΣΤΗΜΗ ΤΩΝ ΔΕΔΟΜΕΝΩΝ\ΔΙΠΛΩΜΑΤΙΚΗ\CSV Files"
        r"\5. Long Horizon And Features Addition\DATASET_FOREX_ML_READY_v3.csv"
    ),
    "INDICES": (
        r"C:\Users\grego\OneDrive\Υπολογιστής\Π.Μ.Σ. ΣΤΗΝ ΑΝΑΛΥΤΙΚΗ ΤΩΝ ΕΠΙΧΕΙΡΗΣΕΩΝ & "
        r"ΣΤΗΝ ΕΠΙΣΤΗΜΗ ΤΩΝ ΔΕΔΟΜΕΝΩΝ\ΔΙΠΛΩΜΑΤΙΚΗ\CSV Files"
        r"\5. Long Horizon And Features Addition\DATASET_INDICES_ML_READY_v3.csv"
    ),
    "STOCKS": (
        r"C:\Users\grego\OneDrive\Υπολογιστής\Π.Μ.Σ. ΣΤΗΝ ΑΝΑΛΥΤΙΚΗ ΤΩΝ ΕΠΙΧΕΙΡΗΣΕΩΝ & "
        r"ΣΤΗΝ ΕΠΙΣΤΗΜΗ ΤΩΝ ΔΕΔΟΜΕΝΩΝ\ΔΙΠΛΩΜΑΤΙΚΗ\CSV Files"
        r"\5. Long Horizon And Features Addition\DATASET_STOCKS_ML_READY_v3.csv"
    ),
}

# Folder used by the optional split-dump utility.
DEFAULT_OUTPUT_DIR = (
    r"C:\Users\grego\OneDrive\Υπολογιστής\Π.Μ.Σ. ΣΤΗΝ ΑΝΑΛΥΤΙΚΗ ΤΩΝ ΕΠΙΧΕΙΡΗΣΕΩΝ & "
    r"ΣΤΗΝ ΕΠΙΣΤΗΜΗ ΤΩΝ ΔΕΔΟΜΕΝΩΝ\ΔΙΠΛΩΜΑΤΙΚΗ\Code Files"
    r"\3. Model Training Python File\Output of ml_preprocessing_v4"
)

# Folder used to save the full terminal output generated by this script.
TERMINAL_OUTPUT_DIR = (
    r"C:\Users\grego\OneDrive\Υπολογιστής\Π.Μ.Σ. ΣΤΗΝ ΑΝΑΛΥΤΙΚΗ ΤΩΝ ΕΠΙΧΕΙΡΗΣΕΩΝ & "
    r"ΣΤΗΝ ΕΠΙΣΤΗΜΗ ΤΩΝ ΔΕΔΟΜΕΝΩΝ\ΔΙΠΛΩΜΑΤΙΚΗ\Terminal Outputs"
    r"\Output of ml_preprocessing_v4"
)


# ============================================================
# DATA LOADING FUNCTIONS
# ============================================================

def get_dataset_path(dataset_name):
    """Returns the full path of the requested dataset."""
    dataset_name = dataset_name.upper()
    if dataset_name not in DATASET_PATHS:
        raise ValueError(
            f"Unknown dataset_name: '{dataset_name}'. "
            f"Available options: {list(DATASET_PATHS.keys())}"
        )
    return DATASET_PATHS[dataset_name]


def load_dataset(dataset_name):
    """Loads one of the 4 ML-ready v3 datasets."""
    path = get_dataset_path(dataset_name)
    if not os.path.exists(path):
        raise FileNotFoundError(f"Dataset file not found: {path}")
    print(f"\nLoading dataset: {dataset_name}")
    print(f"   Path: {path}")
    df = pd.read_csv(path)
    print(f"   Loaded successfully with shape: {df.shape}")
    return df


def load_all_datasets():
    return {name: load_dataset(name) for name in DATASET_PATHS.keys()}


# ============================================================
# VALIDATION & HELPER FUNCTIONS
# ============================================================

def validate_input_dataframe(df, target_col):
    required_cols = ["Date", "Ticker", target_col]
    missing = [col for col in required_cols if col not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")
    if df.empty:
        raise ValueError("Input DataFrame is empty.")

    df = df.copy()
    df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
    if df["Date"].isna().any():
        raise ValueError("Some values in 'Date' could not be converted to datetime.")

    df = df.sort_values(["Date", "Ticker"]).reset_index(drop=True)

    if df[target_col].isna().all():
        raise ValueError(f"Target column '{target_col}' contains only NaN values.")

    return df


def get_target_columns(df):
    return [col for col in df.columns if col.startswith("Target_")]


def get_feature_columns(df, target_col, drop_date=True, drop_ticker=True, drop_all_targets=True):
    cols_to_drop = []
    if drop_date:
        cols_to_drop.append("Date")
    if drop_ticker:
        cols_to_drop.append("Ticker")
    if drop_all_targets:
        cols_to_drop.extend(get_target_columns(df))
    else:
        cols_to_drop.append(target_col)
    cols_to_drop = [col for col in cols_to_drop if col in df.columns]
    return [col for col in df.columns if col not in cols_to_drop]


def print_class_distribution(y, label="Dataset"):
    counts = pd.Series(y).value_counts(dropna=False).sort_index()
    proportions = pd.Series(y).value_counts(normalize=True, dropna=False).sort_index()
    print(f"\nClass distribution - {label}")
    print("Counts:")
    print(counts.to_dict())
    print("Proportions:")
    print({k: round(v, 4) for k, v in proportions.to_dict().items()})


def compute_positive_class_weight(y):
    y_series = pd.Series(y).dropna()
    unique_vals = sorted(y_series.unique())
    if set(unique_vals) != {0, 1}:
        print("[WARNING] Positive class weight not computed (target not binary {0,1}).")
        return None
    negatives = (y_series == 0).sum()
    positives = (y_series == 1).sum()
    if positives == 0:
        print("[WARNING] No positive cases found.")
        return None
    weight = negatives / positives
    print(f"\nSuggested positive class weight: {weight:.4f}")
    return weight


# ============================================================
# PER-TICKER MINIMUM HISTORY FILTER
# ============================================================

def filter_min_ticker_history(df, min_ticker_history=500):
    """
    Removes Tickers with fewer than `min_ticker_history` rows. Keeps only
    assets that can produce stable rolling statistics and contribute
    meaningfully to all four chronological folds.
    """
    if min_ticker_history is None or min_ticker_history <= 0:
        return df, []

    ticker_counts = df.groupby("Ticker").size()
    keep_tickers = ticker_counts[ticker_counts >= min_ticker_history].index.tolist()
    drop_tickers = ticker_counts[ticker_counts < min_ticker_history].index.tolist()

    print(
        f"\nMin-history filter (>= {min_ticker_history} rows):"
        f" keeping {len(keep_tickers)} ticker(s), dropping {len(drop_tickers)}."
    )
    if drop_tickers:
        for t in drop_tickers:
            print(f"   - dropped: {t} ({int(ticker_counts[t])} rows)")

    df_out = df[df["Ticker"].isin(keep_tickers)].reset_index(drop=True)
    print(f"   Final row count: {len(df_out)} (was {len(df)})")
    return df_out, drop_tickers


# ============================================================
# HORIZON-AWARE FEATURE SELECTION
# ============================================================

# Long-horizon rolling windows used by long_horizon_and_feature_engineering.py.
_LONG_WINDOWS = (30, 60, 90)
_LONG_LAGS = (5, 10, 21)

# Cyclic calendar features and regime-aware features kept across ALL horizons.
_ALWAYS_KEEP = (
    "month_sin", "month_cos", "dow_sin", "dow_cos",
    "drawdown_from_252d_high", "vol_60d_pct_rank", "return_30d_pct_rank",
)


def get_horizon_feature_list(all_features, horizon):
    """
    Filters the feature list based on trading horizon.

    Day   -> current values + lag1 only
             (drops *_lag2, *_lag5, *_lag10, *_lag21, all rolling aggregates)
    Swing -> current + lag1 + lag2 + lag5 + 30-day rolling aggregates
             (drops *_lag10, *_lag21, 60- and 90-day rolling aggregates)
    Long  -> all features (no filtering)

    Cyclic calendar features and regime-aware features are kept in all
    horizons regardless of the suffix-based filtering rules.
    """
    horizon = str(horizon).lower()
    if horizon not in ("day", "swing", "long"):
        raise ValueError(
            f"Unknown horizon: '{horizon}'. Expected 'day', 'swing', or 'long'."
        )

    if horizon == "long":
        return list(all_features)

    if horizon == "day":
        excluded_lag_suffixes = [f"_lag{k}" for k in (2,) + _LONG_LAGS]
        excluded_window_suffixes = (
            [f"_cum_{w}" for w in _LONG_WINDOWS]
            + [f"_std_{w}" for w in _LONG_WINDOWS]
            + [f"_mean_{w}" for w in _LONG_WINDOWS]
        )
    else:  # swing
        excluded_lag_suffixes = [f"_lag{k}" for k in (10, 21)]
        excluded_window_suffixes = (
            [f"_cum_{w}" for w in (60, 90)]
            + [f"_std_{w}" for w in (60, 90)]
            + [f"_mean_{w}" for w in (60, 90)]
        )

    excluded = tuple(excluded_lag_suffixes + excluded_window_suffixes)
    return [
        col for col in all_features
        if (not col.endswith(excluded)) or (col in _ALWAYS_KEEP)
    ]


# ============================================================
# CLASS IMBALANCE MITIGATION (TIME-SERIES SAFE)
# ============================================================

def apply_temporal_negative_subsampling(
    X_train, y_train, target_positive_ratio=0.25, random_state=42,
):
    """
    Time-series-safe class imbalance mitigation via majority undersampling.
    Keeps ALL positive samples and randomly subsamples the negatives to
    reach the desired positive rate. Apply ONLY to the training set.
    """
    if target_positive_ratio <= 0 or target_positive_ratio >= 1:
        raise ValueError("target_positive_ratio must be in the open interval (0, 1).")

    X_train = X_train.reset_index(drop=True)
    y_train = pd.Series(y_train).reset_index(drop=True)

    pos_idx = y_train.index[y_train == 1].to_numpy()
    neg_idx = y_train.index[y_train == 0].to_numpy()
    n_pos, n_neg = len(pos_idx), len(neg_idx)

    print("\nApplying temporal negative subsampling (train only)")
    print(f"   Original train size:    {len(y_train)}")
    print(f"   Positives:              {n_pos}")
    print(f"   Negatives:              {n_neg}")
    print(f"   Target positive ratio:  {target_positive_ratio:.2f}")

    if n_pos == 0:
        print("   [WARNING] No positives available. Subsampling skipped.")
        return X_train, y_train

    n_neg_target = int(round(n_pos * (1.0 - target_positive_ratio) / target_positive_ratio))
    if n_neg_target >= n_neg:
        print(f"   Current negatives ({n_neg}) already <= target ({n_neg_target}). Skipped.")
        return X_train, y_train

    rng = np.random.default_rng(random_state)
    sampled_neg = rng.choice(neg_idx, size=n_neg_target, replace=False)
    combined_idx = np.sort(np.concatenate([pos_idx, sampled_neg]))

    X_out = X_train.loc[combined_idx].reset_index(drop=True)
    y_out = y_train.loc[combined_idx].reset_index(drop=True)

    new_pos_rate = float(y_out.mean())
    print(f"   Negatives kept:         {n_neg_target}")
    print(f"   New train size:         {len(y_out)}")
    print(f"   New positive rate:      {new_pos_rate:.4f}")
    return X_out, y_out


# ============================================================
# WINSORIZATION (TRAIN-ONLY PERCENTILES)
# ============================================================

# Features bounded by construction; no winsorization needed.
_WINSOR_SKIP = frozenset({
    "month_sin", "month_cos", "dow_sin", "dow_cos",
    "drawdown_from_252d_high", "vol_60d_pct_rank", "return_30d_pct_rank",
})


def compute_winsor_bounds(X_train, lower_pct=0.01, upper_pct=0.99, skip_features=None):
    """
    Computes per-feature 1%/99% winsorization bounds from the training set.
    Bounded features are skipped automatically.
    """
    if skip_features is None:
        skip_features = _WINSOR_SKIP
    bounds = {}
    for col in X_train.columns:
        if col in skip_features:
            continue
        lo = float(X_train[col].quantile(lower_pct))
        hi = float(X_train[col].quantile(upper_pct))
        if not np.isfinite(lo) or not np.isfinite(hi) or lo >= hi:
            continue
        bounds[col] = (lo, hi)
    return bounds


def apply_winsorization(X, bounds):
    """Clips each feature in `X` to the (lo, hi) bounds learned on TRAIN."""
    X_out = X.copy()
    for col, (lo, hi) in bounds.items():
        if col in X_out.columns:
            X_out[col] = X_out[col].clip(lower=lo, upper=hi)
    return X_out


# ============================================================
# 4-WAY CHRONOLOGICAL SPLIT (train / val_select / val_calib / test)
# ============================================================

def chronological_split_4way(
    df,
    train_ratio=0.70,
    val_ratio=0.15,
    test_ratio=0.15,
    purge_gap_days=0,
    inner_purge_days=None,
):
    """
    Chronological 4-way split:
        train -> [purge] -> val_select -> [inner_purge] -> val_calib -> [purge] -> test

    val_select is used for candidate scoring and threshold reporting.
    val_calib is held out and used only for probability calibration.

    Parameters
    ----------
    df : pd.DataFrame
    train_ratio, val_ratio, test_ratio : floats summing to 1.0.
        val_ratio is split internally into val_select (first half)
        and val_calib (second half).
    purge_gap_days : int
        Embargo (in calendar days) between train/val and val/test.
        Aligned with the look-forward of the target.
    inner_purge_days : int or None
        Embargo between val_select and val_calib. If None, defaults
        to purge_gap_days // 2.
    """
    if round(train_ratio + val_ratio + test_ratio, 5) != 1.0:
        raise ValueError("train_ratio + val_ratio + test_ratio must sum to 1.0")
    if purge_gap_days < 0:
        raise ValueError("purge_gap_days must be >= 0")
    if inner_purge_days is None:
        inner_purge_days = max(0, purge_gap_days // 2)

    df = df.copy()
    df["Date"] = pd.to_datetime(df["Date"])
    df = df.sort_values(["Date", "Ticker"]).reset_index(drop=True)

    unique_dates = np.array(sorted(df["Date"].unique()))
    total_dates = len(unique_dates)
    if total_dates < 12:
        raise ValueError("Not enough unique dates to perform a reliable 4-way split.")

    train_end_idx = max(1, int(total_dates * train_ratio) - 1)
    val_end_idx = max(train_end_idx + 1, int(total_dates * (train_ratio + val_ratio)) - 1)
    if val_end_idx >= total_dates:
        val_end_idx = total_dates - 2

    val_mid_idx = train_end_idx + max(1, (val_end_idx - train_end_idx) // 2)

    train_end_date = pd.Timestamp(unique_dates[train_end_idx])
    val_mid_date = pd.Timestamp(unique_dates[val_mid_idx])
    val_end_date = pd.Timestamp(unique_dates[val_end_idx])

    outer_gap = pd.Timedelta(days=purge_gap_days)
    inner_gap = pd.Timedelta(days=inner_purge_days)

    val_select_start_cut = train_end_date + outer_gap
    val_calib_start_cut = val_mid_date + inner_gap
    test_start_cut = val_end_date + outer_gap

    train_df = df[df["Date"] <= train_end_date].copy()
    val_select_df = df[
        (df["Date"] > val_select_start_cut) & (df["Date"] <= val_mid_date)
    ].copy()
    val_calib_df = df[
        (df["Date"] > val_calib_start_cut) & (df["Date"] <= val_end_date)
    ].copy()
    test_df = df[df["Date"] > test_start_cut].copy()

    # Sanity checks.
    for name, part in (
        ("train", train_df), ("val_select", val_select_df),
        ("val_calib", val_calib_df), ("test", test_df),
    ):
        if part.empty:
            raise ValueError(
                f"Split '{name}' is empty. Check dataset size, ratios, and gaps."
            )
    if train_df["Date"].max() >= val_select_df["Date"].min():
        raise ValueError("Date overlap between train and val_select.")
    if val_select_df["Date"].max() >= val_calib_df["Date"].min():
        raise ValueError("Date overlap between val_select and val_calib.")
    if val_calib_df["Date"].max() >= test_df["Date"].min():
        raise ValueError("Date overlap between val_calib and test.")

    split_info = {
        "train_end_date": train_end_date,
        "val_mid_date": val_mid_date,
        "val_end_date": val_end_date,
        "purge_gap_days": purge_gap_days,
        "inner_purge_days": inner_purge_days,
        "train_rows": len(train_df),
        "val_select_rows": len(val_select_df),
        "val_calib_rows": len(val_calib_df),
        "test_rows": len(test_df),
        "train_unique_dates": train_df["Date"].nunique(),
        "val_select_unique_dates": val_select_df["Date"].nunique(),
        "val_calib_unique_dates": val_calib_df["Date"].nunique(),
        "test_unique_dates": test_df["Date"].nunique(),
    }

    print("\n4-way Chronological Split Completed")
    print(
        f"   train: <= {train_end_date.strftime('%Y-%m-%d')} | "
        f"val_sel: <= {val_mid_date.strftime('%Y-%m-%d')} | "
        f"val_cal: <= {val_end_date.strftime('%Y-%m-%d')} | "
        f"test: > {val_end_date.strftime('%Y-%m-%d')} (+{purge_gap_days}d gap)"
    )
    print(
        f"   Rows -> Train: {split_info['train_rows']} | "
        f"Val_Sel: {split_info['val_select_rows']} | "
        f"Val_Cal: {split_info['val_calib_rows']} | "
        f"Test: {split_info['test_rows']}"
    )

    return train_df, val_select_df, val_calib_df, test_df, split_info


# ============================================================
# OPTIONAL FEATURE SCALING
# ============================================================

def scale_features(X_train, X_val_select, X_val_calib, X_test, scaler_type="minmax"):
    """Train-only fit; transform applied to all folds."""
    print(f"\nScaling features ({scaler_type}, train-only fit)...")
    if scaler_type.lower() == "minmax":
        scaler = MinMaxScaler()
    else:
        raise ValueError("Currently supported scaler_type: 'minmax'")

    def _to_df(arr, src):
        return pd.DataFrame(arr, columns=src.columns, index=src.index)

    X_tr = _to_df(scaler.fit_transform(X_train), X_train)
    X_vs = _to_df(scaler.transform(X_val_select), X_val_select)
    X_vc = _to_df(scaler.transform(X_val_calib), X_val_calib)
    X_te = _to_df(scaler.transform(X_test), X_test)
    return X_tr, X_vs, X_vc, X_te, scaler


# ============================================================
# MAIN TABULAR PREPARATION
# ============================================================

def prepare_tabular_data(
    df,
    target_col,
    train_ratio=0.70,
    val_ratio=0.15,
    test_ratio=0.15,
    scale_for_model=False,
    scaler_type="minmax",
    purge_gap_days=0,
    inner_purge_days=None,
    apply_subsampling=False,
    subsampling_ratio=0.25,
    apply_winsor=True,
    winsor_lower_pct=0.01,
    winsor_upper_pct=0.99,
    horizon=None,
    min_ticker_history=500,
    random_state=42,
):
    """
    Main preprocessing for tabular ML models.

    Pipeline order:
        1. Validate input dataframe.
        2. Per-ticker minimum history filter.
        3. Four-way chronological split (train / val_select / val_calib / test).
        4. Horizon-aware feature filtering (optional).
        5. Train-only winsorization (optional).
        6. Train-only scaling (optional, for linear models).
        7. Train-only temporal negative subsampling (optional).

    Returns
    -------
    X_train, y_train,
    X_val_select, y_val_select,
    X_val_calib, y_val_calib,
    X_test, y_test,
    metadata
    """
    df = validate_input_dataframe(df, target_col)

    df, dropped_tickers = filter_min_ticker_history(df, min_ticker_history=min_ticker_history)

    train_df, vs_df, vc_df, test_df, split_info = chronological_split_4way(
        df,
        train_ratio=train_ratio,
        val_ratio=val_ratio,
        test_ratio=test_ratio,
        purge_gap_days=purge_gap_days,
        inner_purge_days=inner_purge_days,
    )

    y_train = train_df[target_col].copy()
    y_val_select = vs_df[target_col].copy()
    y_val_calib = vc_df[target_col].copy()
    y_test = test_df[target_col].copy()

    all_feature_cols = get_feature_columns(
        df, target_col=target_col, drop_date=True, drop_ticker=True, drop_all_targets=True,
    )

    if horizon is not None:
        feature_cols = get_horizon_feature_list(all_feature_cols, horizon)
        print(
            f"\nHorizon-aware feature selection: horizon='{horizon}' -> "
            f"{len(feature_cols)}/{len(all_feature_cols)} features kept."
        )
    else:
        feature_cols = all_feature_cols

    X_train = train_df[feature_cols].copy()
    X_val_select = vs_df[feature_cols].copy()
    X_val_calib = vc_df[feature_cols].copy()
    X_test = test_df[feature_cols].copy()

    # NaN sanity checks.
    for name, X in (
        ("train", X_train), ("val_select", X_val_select),
        ("val_calib", X_val_calib), ("test", X_test),
    ):
        if X.isna().any().any():
            raise ValueError(f"NaN values detected in {name} features.")
    for name, y in (
        ("train", y_train), ("val_select", y_val_select),
        ("val_calib", y_val_calib), ("test", y_test),
    ):
        if y.isna().any():
            raise ValueError(f"NaN values detected in {name} target.")

    # Train-only winsorization.
    winsor_bounds = {}
    if apply_winsor:
        winsor_bounds = compute_winsor_bounds(
            X_train, lower_pct=winsor_lower_pct, upper_pct=winsor_upper_pct,
        )
        print(
            f"\nWinsorization at {winsor_lower_pct:.2%}/{winsor_upper_pct:.2%} "
            f"on {len(winsor_bounds)} features (train-only percentiles)."
        )
        X_train = apply_winsorization(X_train, winsor_bounds)
        X_val_select = apply_winsorization(X_val_select, winsor_bounds)
        X_val_calib = apply_winsorization(X_val_calib, winsor_bounds)
        X_test = apply_winsorization(X_test, winsor_bounds)

    # Train-only scaling.
    scaler = None
    if scale_for_model:
        X_train, X_val_select, X_val_calib, X_test, scaler = scale_features(
            X_train, X_val_select, X_val_calib, X_test, scaler_type=scaler_type,
        )

    # Train-only subsampling.
    if apply_subsampling:
        X_train, y_train = apply_temporal_negative_subsampling(
            X_train, y_train,
            target_positive_ratio=subsampling_ratio,
            random_state=random_state,
        )

    print_class_distribution(y_train, label="Train")
    print_class_distribution(y_val_select, label="Val_Select")
    print_class_distribution(y_val_calib, label="Val_Calib")
    print_class_distribution(y_test, label="Test")

    pos_weight = compute_positive_class_weight(y_train)

    metadata = {
        "split_info": split_info,
        "feature_columns": feature_cols,
        "all_feature_columns": all_feature_cols,
        "target_column": target_col,
        "horizon": horizon,
        "scaler": scaler,
        "winsor_bounds": winsor_bounds,
        "winsor_applied": apply_winsor,
        "recommended_positive_class_weight": pos_weight,
        "apply_subsampling": apply_subsampling,
        "subsampling_ratio": subsampling_ratio if apply_subsampling else None,
        "purge_gap_days": purge_gap_days,
        "inner_purge_days": split_info["inner_purge_days"],
        "min_ticker_history": min_ticker_history,
        "dropped_tickers": dropped_tickers,
    }

    return (
        X_train, y_train,
        X_val_select, y_val_select,
        X_val_calib, y_val_calib,
        X_test, y_test,
        metadata,
    )


# ============================================================
# OPTIONAL: DUMP SPLIT CSVS FOR DEBUGGING
# ============================================================

def dump_splits_to_csv(
    X_train, y_train,
    X_val_select, y_val_select,
    X_val_calib, y_val_calib,
    X_test, y_test,
    output_dir, prefix,
):
    """
    Saves each split (X + y) as a separate CSV under `output_dir`. Useful
    for offline inspection of the actual rows used in training.
    """
    os.makedirs(output_dir, exist_ok=True)
    target_name = y_train.name if y_train.name is not None else "target"

    splits = [
        ("train", X_train, y_train),
        ("val_select", X_val_select, y_val_select),
        ("val_calib", X_val_calib, y_val_calib),
        ("test", X_test, y_test),
    ]
    print(f"\nDumping splits to: {output_dir}")
    for fold_name, X_fold, y_fold in splits:
        df_fold = X_fold.copy()
        df_fold[target_name] = y_fold.values
        path = os.path.join(output_dir, f"{prefix}_{fold_name}.csv")
        df_fold.to_csv(path, index=False)
        print(f"   Saved split: {path} ({len(df_fold)} rows)")


# ============================================================
# DEMO / SELF-TEST EXECUTION
# ============================================================

if __name__ == "__main__":
    log_path = create_terminal_output_log_file()
    original_stdout = sys.stdout

    with open(log_path, "w", encoding="utf-8") as log_file:
        sys.stdout = TeeLogger(original_stdout, log_file)

        try:
            print("=" * 80)
            print("ML PREPROCESSING PIPELINE v4 - SELF-TEST")
            print("=" * 80)
            print(f"Terminal output log file: {log_path}")

            TARGET = "Target_Swing_Win"

            for dataset_name in DATASET_PATHS.keys():
                print("\n" + "=" * 70)
                print(f"PROCESSING DATASET: {dataset_name}")
                print("=" * 70)

                try:
                    df_test = load_dataset(dataset_name)
                except FileNotFoundError as exc:
                    print(f"   [SKIP] {exc}")
                    continue

                result = prepare_tabular_data(
                    df=df_test,
                    target_col=TARGET,
                    train_ratio=0.70,
                    val_ratio=0.15,
                    test_ratio=0.15,
                    scale_for_model=False,
                    purge_gap_days=14,
                    apply_subsampling=True,
                    subsampling_ratio=0.30,
                    apply_winsor=True,
                    horizon="swing",
                    min_ticker_history=500,
                )
                X_tr, y_tr, X_vs, y_vs, X_vc, y_vc, X_te, y_te, meta_tab = result

                print(f"\n[{dataset_name}] X_train      shape: {X_tr.shape}")
                print(f"[{dataset_name}] X_val_select shape: {X_vs.shape}")
                print(f"[{dataset_name}] X_val_calib  shape: {X_vc.shape}")
                print(f"[{dataset_name}] X_test       shape: {X_te.shape}")

            print("\n" + "=" * 80)
            print("ML PREPROCESSING PIPELINE v4 - SELF-TEST COMPLETED")
            print("=" * 80)
            print(f"Terminal output saved to: {log_path}")

        finally:
            sys.stdout = original_stdout
